### ISSUE TITLE
Continue refactoring and maintenance of new array coercion.

### ISSUE THREAD

**Issue by seberg** [seberg/numpy#8]
@mattip if you have time, maybe you can look at the refactor of array coersion (param detection + filling new array). All of this likely needs some refactor.

https://github.com/seberg/numpy/blob/1cff1596f3f596b5d07abc806ae09a11f0a88db6/numpy/core/src/multiarray/ctors.c#L1276

Is the central function which finds the shape and dtype right now. It calls the main function for finding the right DType (only the class, not the actual dtype, e.g. string length!):

https://github.com/seberg/numpy/blob/1cff1596f3f596b5d07abc806ae09a11f0a88db6/numpy/core/src/multiarray/common.c#L829

If the input is string (or another "flexible" dtype) a second pass will be done to figure out the string length. There is some annoying thing around promotion, since `np.array(big_endian_float64_arr)` actually preserves the endianess.

Currently it used mainly through `PyArray_GetArrayParamsFromObject ` (except for the ufunc code). The actually filling then is done by `setArrayFromSequence`, however, if we leave that cache design to store converted `__array__` objects, then we need to replace it with a simpler version using the coercion cache.

There are probably many confusing details here, so lets talk if you look at it and get stuck.

**Comment by mattip** [comment]
Is this on a branch?

**Comment by mattip** [comment]
Going through my old issues, I think we can close this right?
