### ISSUE TITLE
Finish reorganization of "dtype transfer" casting code with new dtypes

### ISSUE THREAD

**Issue by seberg** [seberg/numpy#9]
@mattip the current central function for dtype transfer in NumPy is here:

https://github.com/seberg/numpy/blob/1cff1596f3f596b5d07abc806ae09a11f0a88db6/numpy/core/src/multiarray/dtype_transfer.c#L3444

This function already uses the new code largely, but the input and/or output can be misaligned or byte swapped. In that case `casting_impl->get_transferfunction ` is allowed to pass back dtypes that that are different from the input dtypes.

This means that multiple "casts" are needed (for alignment it is always needed in that sense):

1. Do input cast `input_dtype -> "input_dtype_returned_by casting_impl->get_transferfunction"` (normally this should be byte swapping)
2. Do the actual cast.
3. Do output cast `"output_dtype_returned_by casting_impl->get_transferfunction" -> output_dtype`.

Another example I could imagine/allow: `float -> string` cast always returns `S32`, so the string might need to be shortened or zero padded.

The current machinery uses the `NPY_AUXDATA`, etc. to already implement chaining when necessary, the new should actually be simpler, because 3 steps are always enough.

Right now I have the `get_transferfunction` signature on the DTypes, which is modelled after the existing function. Both are private API, so they can be changed.

**Comment by mattip** [comment]
Going through old issues, I think we can close this, right?
